[project]
name = "fstd2nc"
description = "Converts to netCDF and provides an xarray interface to RPN standard files (from Environment Canada)."
authors = ["Mike Neish"]
channels = ["fortiers", "conda-forge", "nodefaults", "pypi"]
platforms = ["linux-64"]

[tasks.test]
description = "Run package tests"
cmd = "pytest -vrf"


[tasks.lint]
description = "Run lint on package"
cmd = "ruff check fstd2nc"


[tasks.lint-fix]
description = "Run lint-fix on package"
cmd = "ruff check --fix fstd2nc"

[tasks.format]
description = "Run format on package"
cmd = "ruff format fstd2nc"

[tasks.build]
description = "Build package"
cmd = "python -m pip install . -vv --no-deps --no-build-isolation"

[tasks.doc]
description = "Make docs"
cmd = "sphinx-build -b html docs docs/_build/html"

[tasks.get-version]
description = "Check version"
cmd = "python -c \"import fstd2nc; print(fstd2nc.__version__)\""

[tasks.compile-locale]
description = "Compile locale files"
cmd = "cd fstd2nc/locale && make && cd .. && chmod -R 755 locale"

[tasks.conda-build]
cmd = "rm -rf /tmp/conda-build && rattler-build build --recipe-dir conda.recipe --output-dir /tmp/conda-build -c conda-forge -c fortiers"
depends-on = ["compile-locale"]

[tasks.render]
cmd = "conda-smithy rerender"

[tasks.conda-upload]
cmd = "anaconda upload /tmp/conda-build/linux-64/fstd2nc-*.conda -u fortiers"
depends-on = ["conda-build"]

[dependencies]
dask = ">=2023.7.1"
eccc_rpnpy = ">=2.2.0"
iris = ">=2.0"
netcdf4 = "*"
numpy = ">=1.15.3"
pandas = ">=1.5.1"
pip = "*"
progress = "*"
python = ">=3.10.12"
toolz = "*"
xarray = ">=0.10.3"

[feature.dev.dependencies]
anaconda-client = "*"
ipython = "==8.14.0"
myst-parser = "==1.0.0"
nbsphinx = "==0.9.2"
pygments = "==2.12.0"
pytest = "==7.4.0"
ruff = ">=0.0.280"
setuptools = "==58.5.3"
sphinx = "==5.3.0"
sphinx_rtd_theme = "==0.5.1"
sphinx-autodoc-typehints = "==1.21.8"
sphinx-gallery = "==0.13.0"
wheel = "*"
conda-build = "*"


[environments]
dev = ["dev"]

[target.linux-64.dependencies]
